# Generated by Django 5.1.7 on 2025-05-16 21:12

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        # Create the pg_trgm extension if it doesn't exist
        CreateExtension('pg_trgm'),
        
        # Add GIN indexes with trigram operators
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS products_product_name_en_gin_trgm ON products_product USING gin (name_en gin_trgm_ops);
            CREATE INDEX IF NOT EXISTS products_product_name_ar_gin_trgm ON products_product USING gin (name_ar gin_trgm_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS products_product_name_en_gin_trgm;
            DROP INDEX IF EXISTS products_product_name_ar_gin_trgm;
            """
        ),
    ]
