# Generated by Django 5.1.7 on 2025-05-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_index_search_vectors_trigrams"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="nutrition_facts",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
